In [1]:
import numpy as np

In [3]:
a = np.array([[1,2,3,3,1],[6,8,11,10,7]])
a

array([[ 1,  2,  3,  3,  1],
       [ 6,  8, 11, 10,  7]])

In [114]:
mean_a = np.mean(a, axis = 1)
mean_a

array([2. , 8.4])

In [119]:
mean_a.reshape(2,1)

array([[2. ],
       [8.4]])

In [121]:
a_centered = a - mean_a.reshape(2,1)
a_centered

array([[-1. ,  0. ,  1. ,  1. , -1. ],
       [-2.4, -0.4,  2.6,  1.6, -1.4]])

In [122]:
a_c_t = a_centered.transpose()
a_c_t

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

In [123]:
a_centered_sp = 0
for i in range(0, len(a_c_t)-1):
    a_centered_sp += np.dot(a_c_t[i],a_c_t[i+1])


In [124]:
a_centered_sp

1.839999999999998